version: 2.1
jobs:
  test-python:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - run:
          name: Upgrade pip
          command: |
            python -m pip install --upgrade pip
      - run:
          name: Install dependencies
          command: |
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi
      - run:
          name: Run tests
          command: python manage.py test
workflows:
  build-and-test:
    jobs:
      - test-python
