# Generated by Django 5.1.5 on 2025-01-25 07:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('auth_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('auth_token', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(choices=[('1', 'Instructor'), ('2', 'Student')], max_length=100)),
                ('user_id', models.BigIntegerField()),
                ('temp_password', models.CharField(blank=True, max_length=200, null=True)),
                ('temp_password_valid_time', models.DateTimeField(blank=True, null=True)),
                ('total_login_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-auth_id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_type', models.CharField(max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='word_game/images')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-user_id'],
            },
        ),
    ]
