# Generated by Django 5.1.5 on 2025-03-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_instructor_options_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='learning/images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='learning/images'),
        ),
    ]
