services:
  db:
    image: postgres:17
    expose:
      - 5432
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  django-web:
    build: .
    container_name: django-docker
    depends_on:
      - db
    volumes:
      - staticfiles:/app/static/
    env_file:
      - .env
    ports:
      - "8001:8000"      

  nginx:
    image: nginx:latest
    ports:
      - "80:80" #8001:80
    volumes:
      - ./static:/static:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django-web

volumes:
  staticfiles:
  postgres_data:
